# 第二章 Numpy入门
本章和第 3 章将介绍通过 Python 有效导入、存储和操作内存数据的主要技巧。这个主题非常广泛，因为数据集的来源与格式都十分丰富，比如文档集合、图像集合、声音片段集合、数值数据集合，等等。这些数据虽然存在明显的异构性，但是将所有数据简单地看作数字数组非常有助于我们理解和处理数据。
## 2.1 理解python中的数据类型

In [9]:
import numpy as np
import array
L = list(range(10))
A = array.array('i',L) # i 为数据类型码，表示为整型
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.array([1,4,6,2,7]) # 整型

array([1, 4, 6, 2, 7])

In [11]:
# NumPy 要求数组必须包含同一类型的数据。如果类型不匹配，NumPy 将会向上转换（如果可行）
np.array([1.2,4,6,8,9]) # 浮点型

array([1.2, 4. , 6. , 8. , 9. ])

In [12]:
# type 指定数据的数据类型
np.array([1,4,6,2,7], dtype='float32')

array([1., 4., 6., 2., 7.], dtype=float32)

In [14]:
# 嵌套列表构成的多维数据
np.array([range(i, i +3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 从头创建数据

In [16]:
# 创建一个长度为10的数组，数组的值都是0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# 创建一个3×5的浮点型数组，数组的值都是1
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# 创建一个3×5的浮点型数组，数组的值都是3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# 创建一个数组，数组的值是线性序列
# 从0开始，到20结束，步长为2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# 创建一个5个元素的数组，这5个数均匀的分配到0~1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# 创建一个3×3的、在0~1均匀分布的随机数组成的数组
np.random.random((3,3))

array([[0.34257625, 0.15760412, 0.64057604],
       [0.09408527, 0.10391708, 0.3301986 ],
       [0.88648974, 0.36104166, 0.04369058]])

In [27]:
# 创建一个3×3的、均值为0、方差为1的正态分布的随机数数组
np.random.normal(0,1,(3,3))

array([[-0.23662001, -0.65484761,  0.03916343],
       [ 0.38600157,  0.89412236, -0.52917506],
       [-1.56499563, -2.03598618, -0.80146018]])

In [28]:
# 创建一个3×3的、[0,10)区间的随机整型数组
np.random.randint(0, 10,(3,3))

array([[4, 4, 9],
       [6, 3, 6],
       [8, 7, 5]])

In [29]:
# 创建一个3×3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# 创建一个由3个整形数组成的未初始化的数据
# 数据的值是内存空间中的任意值
np.empty(3)

array([1., 1., 1.])

### NumPy标准数据类型


|数据类型|描述|
| :--: | :--: |
|bool_|布尔值（真、True 或假、False），用一个字节存储|
|int_|默认整型（类似于 C 语言中的 long，通常情况下是 int64 或 int32）|
|intc|同 C 语言的 int 相同（通常是 int32 或 int64）|
|intp|用作索引的整型（和 C 语言的 ssize_t 相同，通常情况下是 int32 或 int64）|
|int8|字节（byte，范围从 –128 到 127）|
|int16|整型（范围从 –32768 到 32767）|
|int32|整型（范围从 –2147483648 到 2147483647）|
|int64|整型（范围从 –9223372036854775808 到 9223372036854775807）|
|uint8|无符号整型（范围从 0 到 255）|
|uint16|无符号整型（范围从 0 到 65535）|
|uint32|无符号整型（范围从 0 到 4294967295）|
|uint64|无符号整型（范围从 0 到 18446744073709551615）|
|float_|float64 的简化形式|
|float16|半精度浮点型：符号比特位，5 比特位指数（exponent），10 比特位尾数（mantissa）|
|float32|单精度浮点型：符号比特位，8 比特位指数，23 比特位尾数|
|float64|双精度浮点型：符号比特位，11 比特位指数，52 比特位尾数|
|complex_|complex128 的简化形式|
|complex64|复数，由两个 32 位浮点数表示|
|complex128|复数，由两个 64 位浮点数表示|


## 2.2 NumPy数组基础
数组的属性  
    确定数组的大小、形状、存储大小、数据类型。  

数组的索引  
    获取和设置数组各个元素的值。  

数组的切分  
    在大的数组中获取或设置更小的子数组。 

数组的变形  
    改变给定数组的形状。    
    
数组的拼接和分裂  
    将多个数组合并为一个，以及将一个数组分裂成多个。

### NumPy数组的属性

In [4]:
import numpy as np
np.random.seed(0) # 设置随机数种子
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [5]:
print("x3 ndim: ",x3.ndim) # 维度
print("x3 shape: ",x3.shape) # 各维度大小
print("x3 size: ",x3.size) # 数组总大小

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [ ]:
import matplotlib.pyplot as plt

plt.figure()