# 2 序列构成的数组
## 2.1内置序列类型
- 容器序列：list、tuple 和 collections.deque 这些序列能存放不同类型的数据。
- 扁平序列：str、bytes、bytearray、memoryview 和 array.array，这类序列只能容纳一种类型。


序列类型还能按照能否被修改来分类。
- 可变序列：list、bytearray、array.array、collections.deque 和 memoryview。
- 不可变序列：tuple、str 和 bytes。
## 2.2 列表推导和生成器表达式
### 2.2.1 列表推导

In [3]:
symble = "$¢£¥€¤"
codes = [ord(x) for x in symble if ord(x) > 100]
print('列表推导：', codes)
codes = list(filter(lambda x: x > 100, map(ord, symble)))
print('filter/map组合：', codes)


列表推导： [162, 163, 165, 8364, 164]
filter/map组合： [162, 163, 165, 8364, 164]


In [4]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
print('笛卡尔积：', tshirts)


笛卡尔积： [('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]


### 2.2.2 生成器表达式 
生成器表达式的语法跟列表推导差不多，只不过把方括号换成圆括号而已。

In [5]:
# 生成器表达式逐个产出元素，从来不会一次性产出一个含有 6 个 T 恤样式的列表。
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirts in (('%s %s') % (c, s) for c in colors for s in sizes):
    print(tshirts)


black S
black M
black L
white S
white M
white L


## 2.3 元组不仅仅时不可变的列表
### 2.3.1 元组和记录
如果只把元组理解为不可变的列表，那其他信息——它所含有的元素的总数和它们的位置——似乎就变得可有可无。但是如果把元组当作一些字段的集合，那么数量和位置信息就变得非常重要了。

In [6]:
# 经纬度
lax_coordinates = (33, -118)
# 市名、年份、人口（单位：百万）、人口变化（单位：百分比）和面积（单位：平方千米）
city, year, pop, chg, area = ('Tokyp', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'CE342567')]
for passport in traveler_ids:
    print('%s/%s' % passport)


USA/31195855
BRA/CE342567
ESP/CE342567


### 2.3.2 元组拆包
将元组中的元素分别赋值给不同的变量，可用 * 来表示忽略多余的元素

In [11]:
latitude, longitude = lax_coordinates
print('latitude:', latitude, '\nlongitude:', longitude, '\n')

_, longitude = lax_coordinates  # 使用_占位符取到想要的数据
print('longitude:', longitude, '\n')

a, b, *rest = range(5)  # 用*来处理剩下的元素
print(a, b, rest)


latitude: 33 
longitude: -118 

longitude: -118 

0 1 [2, 3, 4]


### 2.3.3 嵌套元组拆包
接受表达式的元组可以是嵌套式的，例如 (a, b, (c, d))。

In [12]:
# 每个元组内有 4 个元素，其中最后一个元素是一对坐标。
# 我们把输入元组的最后一个元素拆包到由变量构成的元组里，这样就获取了坐标。
# if longitude <= 0: 这个条件判断把输出限制在西半球的城市。
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))


                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


### 2.3.4 具名元组
collections.namedtuple 是一个工厂函数，它可以用来构建一个带字段名的元组和一个有名字的类——这个带名字的类对调试程序有很大帮助。

In [23]:
from collections import namedtuple
City = namedtuple("City","name country population coordinates")
tokyo = City("Tokyo",'JP',36,(35,139))
print(tokyo)
print(tokyo.name)
print(tokyo[1])

print('*'*10+'具名元组的属性和方法'+'*'*10)
print(City._fields) # 输出包含类所有字段名称的元组
LatLong = namedtuple("LatLong","lar long")
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data) # 用_make()通过接受一个可迭代对象来生成类的实例
print(delhi._asdict()) # _asdict()把具名元组以collections.OrderedDict的形式返回

print('*'*20)
for k,v in delhi._asdict().items():
    print(k,'：',v)


City(name='Tokyo', country='JP', population=36, coordinates=(35, 139))
Tokyo
JP
**********具名元组的属性和方法**********
('name', 'country', 'population', 'coordinates')
{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lar=28.613889, long=77.208889)}
********************
name ： Delhi NCR
country ： IN
population ： 21.935
coordinates ： LatLong(lar=28.613889, long=77.208889)


## 2.4 切片

## 2.5 对序列使用+和*
如果在 a * n 这个语句中，序列 a 里的元素是对其他可变对象的引用的话，你就需要格外注意了

In [29]:
print('\n'+'*'*10+'写法一'+'*'*10+'\n')
board = [['_']*3 for i in range(3)]
print(board)
board[1][2] = 'x'
print(board)
print('\n'+'*'*10+'写法二'+'*'*10+'\n')
board = [['_']*3]*3
print(board)
board[1][2] = 'x'
print(board)


**********写法一**********

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'x'], ['_', '_', '_']]

**********写法二**********

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'x'], ['_', '_', 'x'], ['_', '_', 'x']]


## 2.6 序列的增量赋值
增量赋值运算符 += 和 *= 的表现取决于它们的第一个操作对象。

In [31]:
# 可变序列
l = [1,2,3]
print(id(l)) # 刚开始时列表的 ID。
l *= 2
print(l)
print(id(l)) # 运用增量乘法后，列表的 ID 没变，新元素追加到列表上。
# 不可变序列
t  = (1,2,3)
print(id(t)) # 元组最开始的 ID。
t *= 2
print(t)
print(id(t)) # 运用增量乘法后，新的元组被创建。

2486609198656
[1, 2, 3, 1, 2, 3]
2486609198656
2486582196224
(1, 2, 3, 1, 2, 3)
2486609172320


## 2.7 list.sort 方法和内置函数sorted
list.sort 方法会就地排序列表，也就是说不会把原列表复制一份。这也是这个方法的返回值是 None 的原因，提醒你本方法不会新建一个列表。在这种情况下返回 None 其实是Python 的一个惯例：如果一个函数或者方法对对象进行的是就地改动，那它就应该返回None，好让调用者知道传入的参数发生了变动，而且并未产生新的对象。
   
与 list.sort 相反的是内置函数 sorted，它会新建一个列表作为返回值。这个方法可以接受任何形式的可迭代对象作为参数，甚至包括不可变序列或生成器（见第 14 章）。而不管sorted 接受的是怎样的参数，它最后都会返回一个列表。

In [32]:
# 参数：
# reverse : 是否降序 True/False
# key     : 一个只有一个参数的函数，默认为恒等函数。例：str.lower、len。
fruits = ['grape','respberry','apple','banana']
print(sorted(fruits))
print(fruits)
print(sorted(fruits,reverse=True))
print(sorted(fruits,key=len))

print(fruits.sort())
print(fruits)

['apple', 'banana', 'grape', 'respberry']
['grape', 'respberry', 'apple', 'banana']
['respberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'respberry']
None
['apple', 'banana', 'grape', 'respberry']


## 2,8 用bisect来管理已排序的序列
bisect 模块包含两个主要函数，bisect 和 insort，两个函数都利用二分查找算法来在有序序列中查找或插入元素。
### 2.8.1 用bisect来搜索
bisect(haystack, needle) 在 haystack（干草垛）里搜索 needle（针）的位置，该位置满足的条件是，把 needle 插入这个位置之后，haystack 还能保持升序。也就是在说这个函数返回的位置前面的值，都小于或等于 needle 的值。

In [45]:
import bisect
import sys
HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]
ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'
print('DEMO:', bisect.bisect.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
for needle in reversed(NEEDLES):
    position = bisect.bisect(HAYSTACK, needle)
    offset = position * '  |'
    print(ROW_FMT.format(needle, position, offset))

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


### 2.8.2 用bisect.insert插入新元素
insort(seq, item) 把变量 item 插入到序列 seq 中，并能保持 seq 的升序顺序。

In [53]:
import bisect
import random
SIZE=7
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

 0 -> [0]
 2 -> [0, 2]
13 -> [0, 2, 13]
 4 -> [0, 2, 4, 13]
 8 -> [0, 2, 4, 8, 13]
 5 -> [0, 2, 4, 5, 8, 13]
13 -> [0, 2, 4, 5, 8, 13, 13]


## 2.9 当列表不是首选
虽然列表既灵活又简单，但面对各类需求时，我们可能会有更好的选择。比如，要存放1000 万个浮点数的话，数组（array）的效率要高得多，因为数组在背后存的并不是 float对象，而是数字的机器翻译，也就是字节表述。这一点就跟 C 语言中的数组一样。再比如说，如果需要频繁对序列做先进先出的操作，deque（双端队列）的速度应该会更快。
### 2.9.1 数组
如果我们需要一个只包含数字的列表，那么 array.array 比 list 更高效。数组支持所有跟可变序列有关的操作，包括 .pop、.insert 和 .extend。另外，数组还提供从文件读取和存入文件的更快的方法，如 .frombytes 和 .tofile。

In [7]:
from array import array
from random import random
float = array('d',(random() for i in range(10)))
# 存入文件
fp = open('floats.bin', 'wb')
float.tofile(fp)
fp.close()
# 从文件读取
float2 = array('d')
fp = open('floats.bin', 'rb')
float2.fromfile(fp, 10)
fp.close()

print(float == float2)

True


### 2.9.2 内存视图
memoryview 是一个内置类，它能让用户在不复制内容的情况下操作同一个数组的不同切片。

### 2.9.3 Numpy 和 Scipy
NumPy 实现了多维同质数组（homogeneous array）和矩阵，这些数据结构不但能处理数字，还能存放其他由用户定义的记录。通过 NumPy，用户能对这些数据结构里的元素进行高效的操作。

SciPy 是基于 NumPy 的另一个库，它提供了很多跟科学计算有关的算法，专为线性代数、数值积分和统计学而设计。

In [7]:
import numpy
a = numpy.arange(12)
print('a      : ',a,'\ntype(a): ',type(a),'\na.shape: ',a.shape)
a.shape = 3,4
print(a)
print(a.transpose())

a      :  [ 0  1  2  3  4  5  6  7  8  9 10 11] 
type(a):  <class 'numpy.ndarray'> 
a.shape:  (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 2.9.4 双向队列和其他形式的队列
collections.deque 类（双向队列）是一个线程安全、可以快速从两端添加或者删除元素的数据类型。

In [9]:
from collections import deque
dq = deque(range(10), maxlen=10)
print(dq)
dq.rotate(3)
print(dq)
dq.rotate(-4)
print(dq)
dq.appendleft(-1)
print(dq)


deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)


# 3 字典和集合
本章内容的大纲如下：
- 常见的字典方法
- 如何处理查找不到的键
- 标准库中 dict 类型的变种
- set 和 frozenset 类型
- 散列表的工作原理
- 散列表带来的潜在影响（什么样的数据类型可作为键、不可预知的顺序，等等）
 ## 3.1 泛映射类型  

In [1]:
a = dict(one = 1, two = 2, three = 3)
b = {'one':1, 'two':2, 'three':3}
c = dict(zip(['one','two','three'],[1,2,3]))
d = dict([('one',1),('two',2),('three',3)])
e = dict({'three':3,'two':2,'one':1})
a == b == c == d == e

True

## 3.2 字典推导
字典推导（dictcomp）可以从任何以键值对作为元素的可迭代对象中构建出字典

In [4]:
DIAL_CODES = [(86, 'China'),
              (91, 'India'),
              (1, 'United States'),
              (62, 'Indonesia')]
country_codes = {country:code for code, country in DIAL_CODES}
print(country_codes)

codes_country ={code:country for code, country in DIAL_CODES  if code > 50 }
print(codes_country)

{'China': 86, 'India': 91, 'United States': 1, 'Indonesia': 62}
{86: 'China', 91: 'India', 62: 'Indonesia'}


## 3.3 常见的映射方法
映射类型的方法： dict、collections.defaultdict和collections.OrderedDict

In [14]:
# 用setdefauflt处理找不到的键
'''
当字典 d[k] 不能找到正确的键的时候，Python 会抛出异常，这个行为符合 Python 所信奉的
“快速失败”哲学。也许每个 Python 程序员都知道可以用 d.get(k, default) 来代替 d[k]，
给找不到的键一个默认的返回值（这比处理 KeyError 要方便不少）。但是要更新某个键对应
的值的时候，不管使用 __getitem__ 还是 get 都会不自然，而且效率低。
'''
d = {'one':[1]}

d.setdefault('one', [1]).append(2)
print(d)
# 上下效果等价，只不过后者至少要进行两次键查询——如果键不存在的话，就是三次，用 setdefault 只需要一次就可以完成整个操作。
if 'one' not in dict:
    d['one']=[1]
d['one'].append(3)
print(d)

{'one': [1, 2]}
{'one': [1, 2, 3]}


## 3.4 映射的弹性键查询
有时候为了方便起见，就算某个键在映射里不存在，我们也希望在通过这个键读取值的时候能得到一个默认值。有两个途径能帮我们达到这个目的，一个是通过 defaultdict 这个类型而不是普通的 dict，另一个是给自己定义一个 dict 的子类，然后在子类中实现__missing__ 方法。
### 3.4.1 defaultdict:处理找不到的键的一个选择

In [18]:
import collections
index = collections.defaultdict(list)
index['one']

[]

### 3.4.2 特殊方法__missing__

In [4]:

class StrKeyDict0(dict):
    def __missing__(self, key):
        if isinstance(key, str):
            raise KeyError(key)
        return self[str(key)]
    def get(self, key, default=None):
        try:
            return self[key]
        except KeyError:
            return default
    def __contains__(self, key):
        return key in self.keys() or str(key) in self.keys()


d = StrKeyDict0({'1':1, '2':2, '3':3})
d[2]

2

## 3.5 字典的变种
- collections.OrderedDict 
   
这个类型在添加键的时候会保持顺序，因此键的迭代次序总是一致的。OrderedDict的 popitem 方法默认删除并返回的是字典里的最后一个元素，但是如果像 my_odict.popitem(last=False) 这样调用它，那么它删除并返回第一个被添加进去的元素。

- collections.ChainMap  

该类型可以容纳数个不同的映射对象，然后在进行键查找操作的时候，这些对象会被当作一个整体被逐个查找，直到键被找到为止。这个功能在给有嵌套作用域的语言做解释器的时候很有用，可以用一个映射对象来代表一个作用域的上下文。

- collections.Counter
  
这个映射类型会给键准备一个整数计数器。每次更新一个键的时候都会增加这个计数器。所以这个类型可以用来给可散列表对象计数，或者是当成多重集来用——多重集合就是集合里的元素可以出现不止一次。Counter 实现了 + 和 - 运算符用来合并记录，还有像 most_common([n]) 这类很有用的方法。most_common([n]) 会按照次序返回映射里最常见的 n 个键和它们的计数。

## 3.6子类化UserDict


In [ ]:
import collections
class StrKeyDict(collections.UserDict):

    def __missing__(self,key):
        if isinstance(key,str):
            raise KeyError(key)
        return self[str(key)]
    
    def __contains__(self, key):
        return str(key) in self.data
    
    def __setitem__(self, key, item):
        self.data[str(key)] = item


## 3.7 不可变映射类型

In [7]:
from types import MappingProxyType
d = {'1':'A'}
d_proxy = MappingProxyType(d)
print(d_proxy['1'])
d_proxy['2'] = 'X'

A


TypeError: 'mappingproxy' object does not support item assignment

In [10]:
d['2'] = 'B'
print(d_proxy)
print(d_proxy['2'])

{'1': 'A', '2': 'B'}
B


## 3.8 集合论
集合的本质是许多唯一对象的聚集。因此，集合可以用于去重。

In [15]:
set1 = set([1, 2, 3, 4, 5])
set2 = set([3, 4, 5, 6, 7, 8])
################################

found1 = len(set1 & set2)

################################

found2 = 0
for n in set1:
    if n in set2:
        found2 += 1

################################

found3 = len(set1.intersection(set2))

################################
found1 == found2 == found3

True

### 3.8.1 集合字面量



In [20]:
s = {1,2,3}
print(type(s))
print(frozenset(range(10)))

<class 'set'>
frozenset({0, 1, 2, 3, 4, 5, 6, 7, 8, 9})


### 3.8.2 集合推导

In [22]:
from unicodedata import name
print({chr(i) for i in range(32, 256) if 'SIGN' in name(chr(i),'')})

{'£', '+', '±', '%', '°', '§', '×', '$', '¶', '>', '=', '®', '#', '¬', 'µ', '<', '¢', '¤', '÷', '¥', '©'}


### 3.8.3 集合的操作

In [37]:
set1 = set([1, 2, 3, 4, 5])
set2 = set([3, 4, 5, 6, 7, 8])
print(set1 | set2) # 合集       set1.union(set2)
print(set1 & set2) # 交集       set1.intersection(set2)
print(set1 - set2) # 差集       set1.difference(set2)
print(set1 ^ set2) # 对称差集   set1.symmetric_difference(set2)


{1, 2, 3, 4, 5, 6, 7, 8}
{3, 4, 5}
{1, 2}
{1, 2, 6, 7, 8}


# 4 文本和字节序列
## 4.1 字符问题

In [39]:
s = 'café'
print(len(s))
b = s.encode()
print(b,len(b),b.decode())

4
b'caf\xc3\xa9' 5 café


## 4.2 字节概要

In [4]:
cafe = bytes('café', encoding='utf-8')
print(cafe,'\n',cafe[0],'\n',cafe[:1])


b'caf\xc3\xa9' 
 99 
 b'c'


In [39]:
import pandas as pd

def goodbad(df):
    names = {'0': (df['y']==0).sum() / len(df['y']),
             '1': (df['y']==1).sum() / len(df['y'])}
    return pd.Series(names)

data = pd.DataFrame({'x':['A','A','C','B','E','F','G','H'],
                     'y':[0,1,0,1,0,0,1,1]})

data.groupby('x').apply(goodbad)

0    1
x          
A  0.5  0.5
B  0.0  1.0
C  1.0  0.0
E  1.0  0.0
F  1.0  0.0
G  0.0  1.0
H  0.0  1.0

# 第5章 一等函数
- 在运行时创建
- 能赋值给变量或数据结构中的元素
- 能作为参数传给函数
- 能作为函数的返回结果
## 5.1 把函数视为对象

In [2]:
def factorial(n):
    "return n!"
    return 1 if n < 2 else n*factorial(n-1)

factorial(10),factorial.__doc__,type(factorial)

(3628800, 'return n!', function)

In [3]:
fact = factorial
fact

<function __main__.factorial(n)>

In [4]:
fact(5)

120

In [5]:
map(factorial,range(10))

In [6]:
list(map(factorial,range(10)))

[1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880]

## 5.2 高阶函数
接受函数为参数，或者把函数作为结果返回的函数是高阶函数

In [8]:
# 示例：根据单词长度给一个列表排序
fruits = ['strawberry', 'fig', 'apple', 'cherry', 'raspberry', 'banana']
sorted(fruits,key=len)

['fig', 'apple', 'cherry', 'banana', 'raspberry', 'strawberry']

In [9]:
# 示例：根据反向拼写给一个单词列表排序
def reverse(word:str):
    return word[::-1]
sorted(fruits, key=reverse)

['banana', 'apple', 'fig', 'raspberry', 'strawberry', 'cherry']

In [11]:
# map、filter和reduce的现代替代品
# 示例：计算阶乘列表：map和filter与列表推导比较
temp = list(map(fact,range(6))) # 构建 0! 到 5! 的一个阶乘列表。
print(temp)
temp = [fact(x) for x in range(6)] # 使用列表推导执行相同的操作。
print(temp)
temp = list(map(factorial,filter(lambda x:x % 2,range(6)))) # 使用 map 和 filter 计算直到 5! 的奇数阶乘列表。
print(temp)
temp = [factorial(x) for x in range(6) if x % 2] # 使用列表推导做相同的工作，换掉 map 和 filter，并避免了使用 lambda 表达式。
print(temp)

[1, 1, 2, 6, 24, 120]
[1, 1, 2, 6, 24, 120]
[1, 6, 120]
[1, 6, 120]


In [12]:
# 示例：使用reduce和sum计算0~99之和
# 从 Python 3.0 起，reduce 不再是内置函数了。
# 导入 add，以免创建一个专求两数之和的函数。
# 计算 0~99 之和。
# 使用 sum 做相同的求和；无需导入或创建求和函数。
from functools import reduce
from operator import add
reduce(add, range(100)), sum(range(100))

(4950, 4950)

## 5.3 匿名函数
lambda 关键字在 Python 表达式内创建匿名函数。

In [21]:
# 示例：使用lambda表达式反转拼写，然后依此给单词排序
fruits = ['strawberry', 'fig', 'apple', 'cherry', 'raspberry', 'banana']
sorted(fruits, key=lambda x:x[::-1])

['banana', 'apple', 'fig', 'raspberry', 'strawberry', 'cherry']

## 5.4 可调用对象
- **用户定义的函数**：使用def语句或lambda表达式创建
- **内置函数**：使用C语言实现的函数，如len或str.strftime
- **内置方法**：使用C语言实现的方法，如dict.get
- **方法**：在类的定义体中定义的函数
- **类**：调用类时会运行类的 \_\_new\_\_ 方法创建一个实例，然后运行 \_\_init\_\_ 方法，初始化实例，最后把实例返回给调用方。因为 Python 没有 new 运算符，所以调用类相当于调用函数。
- **类的实例**：如果类定义了 \_\_call\_\_ 方法，那么它的实例可以作为函数调用
- **生成器函数**：使用 yield 关键字的函数或方法。调用生成器函数返回的是生成器对象。

## 5.5 用户定义的可调用类型

In [23]:
# 示例：调用BingoCage实例，从打乱的列表中取出一个元素
import random
from typing import Any
class BingoCage:
    def __init__(self,items):
        self._items = list(items)
        random.shuffle(self._items)
    
    def pick(self):
        try:
            return self._items.pop()
        except IndexError:
            raise LookupError('pick from empty BingoCage')
    
    def __call__(self):
        return self.pick()

bingo = BingoCage(range(3))
print(bingo.pick())
print(bingo())
print(callable(bingo))


2
0
True


## 5.6 函数内省

In [24]:
# 示例：列出常规对象没有而函数有的属性
class C:pass
obj = C()
def func():pass
sorted(set(dir(func))-set(dir(obj)))

['__annotations__',
 '__call__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__get__',
 '__globals__',
 '__kwdefaults__',
 '__name__',
 '__qualname__']